### ISSUE TITLE
건물 검색 기능 구현

### ISSUE THREAD

**Issue by holim0** [TRACE-VER2/Web_FrontEnd#39]
## 세부 사항

➡️ 헤더에 있는 검색창을 통해서 건물을 검색할 수 있도록 합니다.

- 지번과 주소를 통해 검색을 구현합니다.

## 구현 목록 

- [x] 검색관련 Redux store 구현
- [x] 검색 시 서버 요청에 필요한 redux-sagas 구현
- [x]  검색 창에 카카오 맵 api 연동
- [x]  검색 결과 마크업 작업
- [x]  검색 결과 렌더링 작업

## api 테스트 여부 

- [x] 테스트 완료 🛠

**Comment by syleemk** [comment]
확인했습니다.

**Comment by holim0** [comment]
테스트만 완료한 상태입니다.

**Comment by ljm9748** [comment]
검색창->카카오 api->서버이용한 검색 순서인가요???

**Comment by holim0** [comment]
@ljm9748  검색창을 클릭하게 되면 주소 검색창이 뜨게 됩니다.  그 후 사용자가 지번을 검색한 후 그 지번에 대해서 서버에 요청을 하게 됩니다.

**Comment by syleemk** [comment]
확인
