### ISSUE TITLE
글쓰기 관련 기능 수정 및 추가

### ISSUE THREAD

**Issue by holim0** [TRACE-VER2/Web_FrontEnd#50]
- [x] 서버 요청에 맞게 코드를 수정 및 추가합니다. 
- [x] 사용자가 주소를 검색하면 건물의 유효성을 먼저 서버를 통해 판단합니다.
- [x] 리덕스 사가 및 액션에 대한 전체적인 리팩토링을 진행합니다.

**Comment by syleemk** [comment]
확인
